FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma 

RUN npm install && npx prisma generate

COPY . . 



EXPOSE 3000

CMD ["sh","-c","npx prisma migrate dev --name init && npm run dev"]